name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)

jobs:
  make-contribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make daily contribution
        run: |
          echo "Hi there! $(date)" >> README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Daily contribution"
          add: "README.md"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main  # Push directly to the default branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
